version: '3.6'

services:
  db:
    container_name: modbot-db
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: samplepassword
    ports:
      - "5432:5432"
    restart: unless-stopped

  new_posts:
    container_name: modbot-new-posts
    image: modbot:latest
    depends_on:
      - db
    env_file:
      template.env
    command: python3 -m feeds.new_posts
    restart: unless-stopped

  new_comments:
    container_name: modbot-new-comments
    image: modbot:latest
    depends_on:
      - db
    env_file:
      template.env
    command: python3 -m feeds.new_comments
    restart: unless-stopped

  mod_log:
    container_name: modbot-mod-log
    image: modbot:latest
    depends_on:
      - db
    env_file:
      template.env
    command: python3 -m feeds.mod_log
    restart: unless-stopped

  sub_mentions:
    container_name: modbot-sub-mentions
    image: modbot:latest
    env_file:
      template.env
    command: python3 -m feeds.sub_mentions
    restart: unless-stopped

  tools:
    container_name: modbot-tools
    image: modbot:tools
    depends_on:
      - db
    env_file:
      template.env
