name: Code Verification

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        id: linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          auto_fix: false
          black_args: "--line-length 120"
          flake8: true
          flake8_args: "--max-line-length=120"
          continue_on_error: false
