name: Code Verification

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run linters
        id: linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          auto_fix: false
          black_args: "--line-length 120"
          flake8: true
          flake8_args: "--max-line-length=120"
          continue_on_error: false
